/**
 * Javascript data for Simple Utopia Spell Data
 */

const ArcaneArt = Object.freeze({
    Evocation: 'Evocation',
    Enchantment: 'Enchantment',
    Illusion: 'Illusion',
    Array: 'Array',
    Necromancy: 'Necromancy',
    Divination: 'Divination',
    Wake: 'Wake',
    Alteration: 'Alteration',
})

const SpellFeature = Object.freeze({
    Summon_Magimatter: 'Summon Magimatter',
    Elemental_Matter: 'Elemental Matter',
    Instant_Elemental: 'Instant Elemental',
    Lingering_Energy: 'Lingering Energy',
    Lingering_Thermal: 'Lingering Thermal',
    Elemental_Imbue: 'Elemental Imbue',
    Muse_I: 'Muse I',
    Muse_II: 'Muse II',
    Muse_III: 'Muse III',
    Muse_IV: 'Muse IV',
    Continuum_I: 'Continuum I',
    Continuum_II: 'Continuum II',
    Continuum_III: 'Continuum III',
    Continuum_IV: 'Continuum IV',
    Continuum_V: 'Continuum V',
    Continuum_VI: 'Continuum VI',
    Delay: 'Delay',
    Disenchant: 'Disenchant',
    Perpetual: 'Perpetual',
    Sensory_Enchantment: 'Sensory Enchantment',
    Sensory_Negation: 'Sensory Negation',
    Sensational_Overwrite: 'Sensational Overwrite',
    Sensory_Masking: 'Sensory Masking',
    Change_Appearance: 'Change Appearance',
    Summon_Image: 'Summon Image',
    Create_Small_Image: 'Create Small Image',
    Create_Medium_Image: 'Create Medium Image',
    Create_Large_Image: 'Create Large Image',
    Terror: 'Terror',
    Confuse: 'Confuse',
    Throw_I: 'Throw I',
    Throw_II: 'Throw II',
    Throw_III: 'Throw III',
    Throw_IV: 'Throw IV',
    Attach: 'Attach',
    Travel: 'Travel',
    Twincast: 'Twincast',
    Preserve: 'Preserve',
    Resuscitate: 'Resuscitate',
    Ressurect: 'Ressurect',
    Kindle: 'Kindle',
    Sever: 'Sever',
    Surveil: 'Surveil',
    Insight: 'Insight',
    Probe: 'Probe',
    Weak_Divulgence: 'Weak Divulgence',
    Strong_Divulgence: 'Strong Divulgence',
    Scry_I: 'Scry I',
    Scry_II: 'Scry II',
    Scry_III: 'Scry III',
    Scry_IV: 'Scry IV',
    Premonition: 'Premonition',
    Locate_Creature: 'Locate Creature',
    Locate_Object: 'Locate Object',
    Shapeless_Extend: 'Shapeless Extend',
    Square_Extend: 'Square Extend',
    Circular_Extend: 'Circular Extend',
    Shapeless_Fulminate: 'Shapeless Fulminate',
    Cubic_Fulminate: 'Cubic Fulminate',
    Spherical_Fulminate: 'Spherical Fulminate',
    Finite_Void: 'Finite Void',
    Cubic_Void: 'Cubic Void',
    Spherical_Void: 'Spherical Void',
    Purify: 'Purify',
    Transmute: 'Transmute',
    Alleviate: 'Alleviate',
    Mend_I: 'Mend I',
    Mend_II: 'Mend II',
    Mend_III: 'Mend III',
    Mend_IV: 'Mend IV',
    Mend_V: 'Mend V',
    Reshape_Object: 'Reshape Object',
    Reshape_Creature: 'Reshape Creature',
    Debilitate: 'Debilitate',
    Telekinetic_Halt: 'Telekinetic Halt',
    Telekinetic_Force: 'Telekinetic Force',
})

const SpellGroup = Object.freeze({
    Magimatter: 'Magimatter',
    Destruction: 'Destruction',
    Imbue: 'Imbue',
    Prolong: 'Prolong',
    Modification: 'Modification',
    Permanency: 'Permanency',
    ExtraSensory: 'ExtraSensory',
    Imagery: 'Imagery',
    Duress: 'Duress',
    Bolster: 'Bolster',
    Revivification: 'Revivification',
    Animation: 'Animation',
    Soul_Rending: 'Soul Rending',
    Unearthing: 'Unearthing',
    Foretelling: 'Foretelling',
    Locating: 'Locating',
    Scope: 'Scope',
    Void: 'Void',
    Alchemy: 'Alchemy',
    Restoration: 'Restoration',
    Transmutation: 'Transmutation',
    Locomotion: 'Locomotion',
})

const SpellFeatures = [
    {
        Art: ArcaneArt.Evocation,
        Group: SpellGroup.Magimatter,
        Name: SpellFeature.Summon_Magimatter,
        Cost: 5,
        Variable: true,
    },
    {
        Art: ArcaneArt.Evocation,
        Group: SpellGroup.Magimatter,
        Name: SpellFeature.Elemental_Matter,
        Cost: 30,
        Variable: false,
    },
    {
        Art: ArcaneArt.Evocation,
        Group: SpellGroup.Destruction,
        Name: SpellFeature.Instant_Elemental,
        Cost: 15,
        Variable: false,
    },
    {
        Art: ArcaneArt.Evocation,
        Group: SpellGroup.Destruction,
        Name: SpellFeature.Lingering_Energy,
        Cost: 25,
        Variable: false,
    },
    {
        Art: ArcaneArt.Evocation,
        Group: SpellGroup.Destruction,
        Name: SpellFeature.Lingering_Thermal,
        Cost: 30,
        Variable: false,
    },
    {
        Art: ArcaneArt.Evocation,
        Group: SpellGroup.Imbue,
        Name: SpellFeature.Elemental_Imbue,
        Cost: 15,
        Variable: false,
    },
    {
        Art: ArcaneArt.Enchantment,
        Group: SpellGroup.Prolong,
        Name: SpellFeature.Muse_I,
        Cost: 10,
        Variable: true,
    },
    {
        Art: ArcaneArt.Enchantment,
        Group: SpellGroup.Prolong,
        Name: SpellFeature.Muse_II,
        Cost: 20,
        Variable: true,
    },
    {
        Art: ArcaneArt.Enchantment,
        Group: SpellGroup.Prolong,
        Name: SpellFeature.Muse_III,
        Cost: 50,
        Variable: true,
    },
    {
        Art: ArcaneArt.Enchantment,
        Group: SpellGroup.Prolong,
        Name: SpellFeature.Muse_IV,
        Cost: 110,
        Variable: true,
    },
    {
        Art: ArcaneArt.Enchantment,
        Group: SpellGroup.Prolong,
        Name: SpellFeature.Continuum_I,
        Cost: 40,
        Variable: true,
    },
    {
        Art: ArcaneArt.Enchantment,
        Group: SpellGroup.Prolong,
        Name: SpellFeature.Continuum_II,
        Cost: 80,
        Variable: true,
    },
    {
        Art: ArcaneArt.Enchantment,
        Group: SpellGroup.Prolong,
        Name: SpellFeature.Continuum_III,
        Cost: 200,
        Variable: true,
    },
    {
        Art: ArcaneArt.Enchantment,
        Group: SpellGroup.Prolong,
        Name: SpellFeature.Continuum_IV,
        Cost: 440,
        Variable: true,
    },
    {
        Art: ArcaneArt.Enchantment,
        Group: SpellGroup.Prolong,
        Name: SpellFeature.Continuum_V,
        Cost: 1000,
        Variable: true,
    },
    {
        Art: ArcaneArt.Enchantment,
        Group: SpellGroup.Prolong,
        Name: SpellFeature.Continuum_VI,
        Cost: 1900,
        Variable: true,
    },
    {
        Art: ArcaneArt.Enchantment,
        Group: SpellGroup.Modification,
        Name: SpellFeature.Delay,
        Cost: 10,
        Variable: true,
    },
    {
        Art: ArcaneArt.Enchantment,
        Group: SpellGroup.Modification,
        Name: SpellFeature.Disenchant,
        Cost: 50,
        Variable: true,
    },
    {
        Art: ArcaneArt.Enchantment,
        Group: SpellGroup.Permanency,
        Name: SpellFeature.Perpetual,
        Cost: 100,
        Variable: false,
    },
    {
        Art: ArcaneArt.Illusion,
        Group: SpellGroup.ExtraSensory,
        Name: SpellFeature.Sensory_Enchantment,
        Cost: 30,
        Variable: false,
    },
    {
        Art: ArcaneArt.Illusion,
        Group: SpellGroup.ExtraSensory,
        Name: SpellFeature.Sensory_Negation,
        Cost: 70,
        Variable: false,
    },
    {
        Art: ArcaneArt.Illusion,
        Group: SpellGroup.ExtraSensory,
        Name: SpellFeature.Sensational_Overwrite,
        Cost: 75,
        Variable: false,
    },
    {
        Art: ArcaneArt.Illusion,
        Group: SpellGroup.ExtraSensory,
        Name: SpellFeature.Sensory_Masking,
        Cost: 80,
        Variable: false,
    },
    {
        Art: ArcaneArt.Illusion,
        Group: SpellGroup.Imagery,
        Name: SpellFeature.Change_Appearance,
        Cost: 50,
        Variable: false,
    },
    {
        Art: ArcaneArt.Illusion,
        Group: SpellGroup.Imagery,
        Name: SpellFeature.Summon_Image,
        Cost: 10,
        Variable: false,
    },
    {
        Art: ArcaneArt.Illusion,
        Group: SpellGroup.Imagery,
        Name: SpellFeature.Create_Small_Image,
        Cost: 30,
        Variable: false,
    },
    {
        Art: ArcaneArt.Illusion,
        Group: SpellGroup.Imagery,
        Name: SpellFeature.Create_Medium_Image,
        Cost: 60,
        Variable: false,
    },
    {
        Art: ArcaneArt.Illusion,
        Group: SpellGroup.Imagery,
        Name: SpellFeature.Create_Large_Image,
        Cost: 120,
        Variable: false,
    },
    {
        Art: ArcaneArt.Illusion,
        Group: SpellGroup.Duress,
        Name: SpellFeature.Terror,
        Cost: 40,
        Variable: false,
    },
    {
        Art: ArcaneArt.Illusion,
        Group: SpellGroup.Duress,
        Name: SpellFeature.Confuse,
        Cost: 70,
        Variable: false,
    },
    {
        Art: ArcaneArt.Array,
        Group: SpellGroup.Bolster,
        Name: SpellFeature.Throw_I,
        Cost: 4,
        Variable: false,
    },
    {
        Art: ArcaneArt.Array,
        Group: SpellGroup.Bolster,
        Name: SpellFeature.Throw_II,
        Cost: 30,
        Variable: false,
    },
    {
        Art: ArcaneArt.Array,
        Group: SpellGroup.Bolster,
        Name: SpellFeature.Throw_III,
        Cost: 210,
        Variable: false,
    },
    {
        Art: ArcaneArt.Array,
        Group: SpellGroup.Bolster,
        Name: SpellFeature.Throw_IV,
        Cost: 1200,
        Variable: false,
    },
    {
        Art: ArcaneArt.Array,
        Group: SpellGroup.Bolster,
        Name: SpellFeature.Travel,
        Cost: 5,
        Variable: true,
    },
    {
        Art: ArcaneArt.Array,
        Group: SpellGroup.Bolster,
        Name: SpellFeature.Twincast,
        Cost: 100,
        Variable: false,
    },
    {
        Art: ArcaneArt.Necromancy,
        Group: SpellGroup.Revivification,
        Name: SpellFeature.Preserve,
        Cost: 50,
        Variable: false,
    },
    {
        Art: ArcaneArt.Necromancy,
        Group: SpellGroup.Revivification,
        Name: SpellFeature.Resuscitate,
        Cost: 100,
        Variable: false,
    },
    {
        Art: ArcaneArt.Necromancy,
        Group: SpellGroup.Animation,
        Name: SpellFeature.Ressurect,
        Cost: 10,
        Variable: true,
    },
    {
        Art: ArcaneArt.Necromancy,
        Group: SpellGroup.Animation,
        Name: SpellFeature.Kindle,
        Cost: 10,
        Variable: true,
    },
    {
        Art: ArcaneArt.Necromancy,
        Group: SpellGroup.Soul_Rending,
        Name: SpellFeature.Sever,
        Cost: 80,
        Variable: false,
    },
    {
        Art: ArcaneArt.Divination,
        Group: SpellGroup.Unearthing,
        Name: SpellFeature.Surveil,
        Cost: 30,
        Variable: false,
    },
    {
        Art: ArcaneArt.Divination,
        Group: SpellGroup.Unearthing,
        Name: SpellFeature.Insight,
        Cost: 50,
        Variable: false,
    },
    {
        Art: ArcaneArt.Divination,
        Group: SpellGroup.Unearthing,
        Name: SpellFeature.Probe,
        Cost: 50,
        Variable: false,
    },
    {
        Art: ArcaneArt.Divination,
        Group: SpellGroup.Unearthing,
        Name: SpellFeature.Weak_Divulgence,
        Cost: 100,
        Variable: false,
    },
    {
        Art: ArcaneArt.Divination,
        Group: SpellGroup.Unearthing,
        Name: SpellFeature.Strong_Divulgence,
        Cost: 250,
        Variable: false,
    },
    {
        Art: ArcaneArt.Divination,
        Group: SpellGroup.Foretelling,
        Name: SpellFeature.Scry_I,
        Cost: 30,
        Variable: false,
    },
    {
        Art: ArcaneArt.Divination,
        Group: SpellGroup.Foretelling,
        Name: SpellFeature.Scry_II,
        Cost: 60,
        Variable: false,
    },
    {
        Art: ArcaneArt.Divination,
        Group: SpellGroup.Foretelling,
        Name: SpellFeature.Scry_III,
        Cost: 90,
        Variable: false,
    },
    {
        Art: ArcaneArt.Divination,
        Group: SpellGroup.Foretelling,
        Name: SpellFeature.Scry_IV,
        Cost: 120,
        Variable: false,
    },
    {
        Art: ArcaneArt.Divination,
        Group: SpellGroup.Foretelling,
        Name: SpellFeature.Premonition,
        Cost: 80,
        Variable: false,
    },
    {
        Art: ArcaneArt.Divination,
        Group: SpellGroup.Locating,
        Name: SpellFeature.Locate_Creature,
        Cost: 100,
        Variable: false,
    },
    {
        Art: ArcaneArt.Divination,
        Group: SpellGroup.Locating,
        Name: SpellFeature.Locate_Object,
        Cost: 100,
        Variable: false,
    },
    {
        Art: ArcaneArt.Wake,
        Group: SpellGroup.Scope,
        Name: SpellFeature.Shapeless_Extend,
        Cost: 5,
        Variable: true,
    },
    {
        Art: ArcaneArt.Wake,
        Group: SpellGroup.Scope,
        Name: SpellFeature.Square_Extend,
        Cost: 20,
        Variable: true,
    },
    {
        Art: ArcaneArt.Wake,
        Group: SpellGroup.Scope,
        Name: SpellFeature.Circular_Extend,
        Cost: 35,
        Variable: true,
    },
    {
        Art: ArcaneArt.Wake,
        Group: SpellGroup.Scope,
        Name: SpellFeature.Shapeless_Fulminate,
        Cost: 10,
        Variable: true,
    },
    {
        Art: ArcaneArt.Wake,
        Group: SpellGroup.Scope,
        Name: SpellFeature.Cubic_Fulminate,
        Cost: 60,
        Variable: true,
    },
    {
        Art: ArcaneArt.Wake,
        Group: SpellGroup.Scope,
        Name: SpellFeature.Spherical_Fulminate,
        Cost: 100,
        Variable: true,
    },
    {
        Art: ArcaneArt.Wake,
        Group: SpellGroup.Void,
        Name: SpellFeature.Finite_Void,
        Cost: 10,
        Variable: false,
    },
    {
        Art: ArcaneArt.Wake,
        Group: SpellGroup.Void,
        Name: SpellFeature.Cubic_Void,
        Cost: 6,
        Variable: true,
    },
    {
        Art: ArcaneArt.Wake,
        Group: SpellGroup.Void,
        Name: SpellFeature.Spherical_Void,
        Cost: 10,
        Variable: true,
    },
    {
        Art: ArcaneArt.Alteration,
        Group: SpellGroup.Alchemy,
        Name: SpellFeature.Purify,
        Cost: 50,
        Variable: false,
    },
    {
        Art: ArcaneArt.Alteration,
        Group: SpellGroup.Alchemy,
        Name: SpellFeature.Transmute,
        Cost: 20,
        Variable: false,
    },
    {
        Art: ArcaneArt.Alteration,
        Group: SpellGroup.Restoration,
        Name: SpellFeature.Alleviate,
        Cost: 80,
        Variable: false,
    },
    {
        Art: ArcaneArt.Alteration,
        Group: SpellGroup.Restoration,
        Name: SpellFeature.Mend_I,
        Cost: 40,
        Variable: true,
    },
    {
        Art: ArcaneArt.Alteration,
        Group: SpellGroup.Restoration,
        Name: SpellFeature.Mend_II,
        Cost: 60,
        Variable: true,
    },
    {
        Art: ArcaneArt.Alteration,
        Group: SpellGroup.Restoration,
        Name: SpellFeature.Mend_III,
        Cost: 80,
        Variable: true,
    },
    {
        Art: ArcaneArt.Alteration,
        Group: SpellGroup.Restoration,
        Name: SpellFeature.Mend_IV,
        Cost: 100,
        Variable: true,
    },
    {
        Art: ArcaneArt.Alteration,
        Group: SpellGroup.Restoration,
        Name: SpellFeature.Mend_V,
        Cost: 120,
        Variable: true,
    },
    {
        Art: ArcaneArt.Alteration,
        Group: SpellGroup.Transmutation,
        Name: SpellFeature.Reshape_Object,
        Cost: 60,
        Variable: false,
    },
    {
        Art: ArcaneArt.Alteration,
        Group: SpellGroup.Transmutation,
        Name: SpellFeature.Reshape_Creature,
        Cost: 100,
        Variable: false,
    },
    {
        Art: ArcaneArt.Alteration,
        Group: SpellGroup.Transmutation,
        Name: SpellFeature.Debilitate,
        Cost: 150,
        Variable: false,
    },
    {
        Art: ArcaneArt.Alteration,
        Group: SpellGroup.Locomotion,
        Name: SpellFeature.Telekinetic_Halt,
        Cost: 10,
        Variable: true,
    },
    {
        Art: ArcaneArt.Alteration,
        Group: SpellGroup.Locomotion,
        Name: SpellFeature.Telekinetic_Force,
        Cost: 10,
        Variable: true,
    },
]
